### PR TITLE
Pass file dataset containing transfer syntax details to on_c_store handler

### PR DESCRIPTION
**Pull request by bvarilone**

### CODE REVIEW

**Comment by AlecBenzer** [comment]
Huh, looks like the master branch isn't protected for our other repos? Should it be? @toddgardner @tkho

**Comment by scaramallion** [comment]
This is definitely something that would be useful for other pynetdicom users. It's already one of the [issues](https://github.com/pydicom/pynetdicom3/issues/65) that needs to be addressed.

I need to check but I think it might be the case that transferring encapsulated datasets requires agreeing to the correct transfer syntax during association negotiation (and failing DIMSE operations that try to use an inappropriate syntax). I have a feeling this isn't done at the moment though.

**Comment by RemiTorracinta** [comment]
@scaramallion If you don't want to build up the encapsulated dataset, it might be nice to pass another argument that at least lets the user know what syntax the DIMSE is trying to use.

**Comment by RemiTorracinta** [comment]
file_meta may need other fields to form a valid encapsulated dicom, but this does not matter with our current usage.

**Pull request merged**
